 --PERSAS CAPA
 CREATE TABLE PERSAS_CAPA(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"SUPRIDORA1" NVARCHAR2(100)
 ,"SUPRIDORA2" NVARCHAR2(100)
 
 );
 
 
 
  --PERSAS MERCADO
 CREATE TABLE PERSAS_MERCADO(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"FORNECIMENTO_MWH" NUMBER(38,8)
 ,"A1_MWH" NUMBER(38,8)
 ,"A2_MWH" NUMBER(38,8)
 ,"A3_MWH" NUMBER(38,8)
 ,"A3A_MWH" NUMBER(38,8)
 ,"A4_MWH" NUMBER(38,8)
 ,"AS_MWH" NUMBER(38,8)
 ,"BT_MWH" NUMBER(38,8)
 ,"MERCADO_BASE_TOTAL_MWH" NUMBER(38,8)
 ,"SUPRIMENTO_MWH" NUMBER(38,8)
 ,"LIVRES_A1_MWH" NUMBER(38,8)
 ,"DEMAIS_LIVRES_MWH" NUMBER(38,8)
 ,"DISTRIBUICAO_MWH" NUMBER(38,8)
 ,"GERADOR_MWH" NUMBER(38,8)
 ,"TOTAL_MWH" NUMBER(38,8)
 ,"NUC" NUMBER(38,8)
 ,"VARIACAO_PERCENT" NUMBER(38,8)
 
 );
 
 
 
  --PERSAS RECEITA
 CREATE TABLE PERSAS_RECEITA(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"FORNECIMENTO_RS" NUMBER(38,8)
 ,"A1_RS" NUMBER(38,8)
 ,"A2_RS" NUMBER(38,8)
 ,"A3_RS" NUMBER(38,8)
 ,"A3A_RS" NUMBER(38,8)
 ,"A4_RS" NUMBER(38,8)
 ,"AS_RS" NUMBER(38,8)
 ,"BT_RS" NUMBER(38,8)
 ,"MERCADO_BASE_TOTAL_RS" NUMBER(38,8)
 ,"SUPRIMENTO_RS" NUMBER(38,8)
 ,"LIVRES_A1_RS" NUMBER(38,8)
 ,"DEMAIS_LIVRES_RS" NUMBER(38,8)
 ,"DISTRIBUICAO_RS" NUMBER(38,8)
 ,"GERADOR_RS" NUMBER(38,8)
 ,"TOTAL_RS" NUMBER(38,8)
 ,"RESIDENCIAL_RS" NUMBER(38,8)
 ,"INDUSTRIAL_RS" NUMBER(38,8)
 ,"COMERCIAL_RS" NUMBER(38,8)
 ,"RURAL_RS" NUMBER(38,8)
 ,"ILUMINACAO_RS" NUMBER(38,8)
 ,"PODER_PUBLICO_RS" NUMBER(38,8)
 ,"SERVICO_PUBLICO_RS" NUMBER(38,8)
 ,"DEMAIS_RS" NUMBER(38,8)

 
 );
 
 
 
 --PERSAS FATOR X
 CREATE TABLE PERSAS_FATOR_X(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"COMPONENTE_PD_PERCENT" NUMBER(38,8)
 ,"COMPONENTE_T_PERCENT" NUMBER(38,8)
 ,"FATOR_X_PERCENT" NUMBER(38,8)
 ,"IGPM_PERCENT" NUMBER(38,8)
 ,"IPCA_PERCENT" NUMBER(38,8)

 
 );
 
 
 --PERSAS INDICES
 CREATE TABLE PERSAS_INDICES(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"IRT_ECONOMICO_PERCENT" NUMBER(38,8)
 ,"IRT_FINANCEIRO_PERCENT" NUMBER(38,8)
 ,"IRT_FINAN_ECON_PERCENT" NUMBER(38,8)
 ,"EFEITO_MEDIO_AT_PERCENT" NUMBER(38,8)
 ,"EFEITO_MEDIO_BT_PERCENT" NUMBER(38,8)
 ,"EFEITO_TARIFA_AT_BT_PERCENT" NUMBER(38,8)
 ,"TARIFA_RESIDEN_B1_RS_MWH" NUMBER(38,8)
 ,"ICMS_PERCENT" NUMBER(38,8)
 ,"PIS_PERCENT" NUMBER(38,8)

 
 );
 
 
 
 --PERSAS DRP
 CREATE TABLE PERSAS_DRP(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"TFSEE_RS" NUMBER(38,8)
,"RGR_RS" NUMBER(38,8)
,"CCC_RS" NUMBER(38,8)
,"CDE_RS" NUMBER(38,8)
,"CFURH_RS" NUMBER(38,8)
,"ESS_EER_RS" NUMBER(38,8)
,"PROINFA_RS" NUMBER(38,8)
,"ONS_RS" NUMBER(38,8)
,"PD_RS" NUMBER(38,8)
,"ENCARGOS_RS" NUMBER(38,8)
,"REDE_BASICA_RS" NUMBER(38,8)
,"REDE_BASICA_FRONTEIRA_RS" NUMBER(38,8)
,"REDE_BASICA_ONS_A2_RS" NUMBER(38,8)
,"REDE_BASICA_EXPORT_A2_RS" NUMBER(38,8)
,"CONEXAO_RS" NUMBER(38,8)
,"MUST_ITAIPU_RS" NUMBER(38,8)
,"TRANSPORTE_ITAIPU_RS" NUMBER(38,8)
,"SISTEMA_DISTRIBUICAO_RS" NUMBER(38,8)
,"TRANSPORTE_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_RS" NUMBER(38,8)
,"PARCELA_A_RS" NUMBER(38,8)
,"PARCELA_B_RS" NUMBER(38,8)
,"RA1_RS" NUMBER(38,8)
,"LIMITE_PARCELA_B_RS" NUMBER(38,8)
,"SUBVENCAO_PARCELA_B_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_MWH" NUMBER(38,8)
,"FORNECIMENTO_SUPRIMENTO_MWH" NUMBER(38,8)
,"FORNECIMENTO_MWH" NUMBER(38,8)
,"SUPRIMENTO_MWH" NUMBER(38,8)
,"CUSTO_MEDIO_RS_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_DISTRIBUICAO_PERCENT" NUMBER(38,8)
,"PERDA_REDE_BASICA_PERCENT" NUMBER(38,8)
,"PERDAS_REGULATORIAS_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_MWH" NUMBER(38,8)
,"PERDA_TECNICA_MWH" NUMBER(38,8)
,"PERDA_DISTRIBUICAO_MWH" NUMBER(38,8)
,"PERDA_RB_DISTRIBUICAO_MWH" NUMBER(38,8)
,"PERDA_RB_CATIVO_MWH" NUMBER(38,8)

 
 );
 
 
 
--PERSAS DRA
 CREATE TABLE PERSAS_DRA(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"SARI" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"REGIAO" NVARCHAR2(100)
 ,"DATA" NVARCHAR2(100)
 ,"TFSEE_RS" NUMBER(38,8)
,"RGR_RS" NUMBER(38,8)
,"CCC_RS" NUMBER(38,8)
,"CDE_RS" NUMBER(38,8)
,"CFURH_RS" NUMBER(38,8)
,"ESS_EER_RS" NUMBER(38,8)
,"PROINFA_RS" NUMBER(38,8)
,"ONS_RS" NUMBER(38,8)
,"PD_RS" NUMBER(38,8)
,"ENCARGOS_RS" NUMBER(38,8)
,"REDE_BASICA_RS" NUMBER(38,8)
,"REDE_BASICA_FRONTEIRA_RS" NUMBER(38,8)
,"REDE_BASICA_ONS_A2_RS" NUMBER(38,8)
,"REDE_BASICA_EXPORT_A2_RS" NUMBER(38,8)
,"CONEXAO_RS" NUMBER(38,8)
,"MUST_ITAIPU_RS" NUMBER(38,8)
,"TRANSPORTE_ITAIPU_RS" NUMBER(38,8)
,"SISTEMA_DISTRIBUICAO_RS" NUMBER(38,8)
,"TRANSPORTE_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_RS" NUMBER(38,8)
,"PARCELA_A_RS" NUMBER(38,8)
,"PARCELA_B_RS" NUMBER(38,8)
,"RA1_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_MWH" NUMBER(38,8)
,"FORNECIMENTO_SUPRIMENTO_MWH" NUMBER(38,8)
,"FORNECIMENTO_MWH" NUMBER(38,8)
,"SUPRIMENTO_MWH" NUMBER(38,8)
,"CUSTO_MEDIO_RS_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_DISTRIBUICAO_PERCENT" NUMBER(38,8)
,"PERDA_REDE_BASICA_PERCENT" NUMBER(38,8)
,"PERDAS_REGULATORIAS_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_MWH" NUMBER(38,8)
,"PERDA_TECNICA_MWH" NUMBER(38,8)
,"PERDA_DISTRIBUICAO_MWH" NUMBER(38,8)
,"PERDA_RB_DISTRIBUICAO_MWH" NUMBER(38,8)
,"PERDA_RB_CATIVO_MWH" NUMBER(38,8)

 
 );
 
 
 --PERSAS CUSTO SUPRIMENTO
 CREATE TABLE "IRARRR01"."PERSAS_CUSTO_SUPRIMENTO" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"SUPRIDORA1" NVARCHAR2(100), 
	"NIVEL_TENSAO1" NVARCHAR2(100), 
	"MWH1" NUMBER(38,8), 
	"DESCONTO1_PERCENT" NUMBER(38,8), 
	"TARIFA1_RS_MWH" NUMBER(38,8), 
	"TARIFA_COBERTURA1_RS_MWH" NUMBER(38,8), 
	"DESCONTO_ANTIGO1_PERCENT" NUMBER(38,8), 
	"SUPRIDORA2" NVARCHAR2(100), 
	"NIVEL_TENSAO2" NVARCHAR2(100), 
	"MWH2" NUMBER(38,8), 
	"DESCONTO2_PERCENT" NUMBER(38,8), 
	"TARIFA2_RS_MWH" NUMBER(38,8), 
	"TARIFA_COBERTURA2_RS_MWH" NUMBER(38,8), 
	"DESCONTO_ANTIGO2_PERCENT" NUMBER(38,8), 
	"SUPRIDORA3" NVARCHAR2(100), 
	"NIVEL_TENSAO3" NVARCHAR2(100), 
	"MWH3" NUMBER(38,8), 
	"DESCONTO3_PERCENT" NUMBER(38,8), 
	"TARIFA3_RS_MWH" NUMBER(38,8), 
	"TARIFA_COBERTURA3_RS_MWH" NUMBER(38,8), 
	"DESCONTO_ANTIGO3_PERCENT" NUMBER(38,8), 
	"SUPRIDORA4" NVARCHAR2(100), 
	"NIVEL_TENSAO4" NVARCHAR2(100), 
	"MWH4" NUMBER(38,8), 
	"DESCONTO4_PERCENT" NUMBER(38,8), 
	"TARIFA4_RS_MWH" NUMBER(38,8), 
	"TARIFA_COBERTURA4_RS_MWH" NUMBER(38,8), 
	"DESCONTO_ANTIGO4_PERCENT" NUMBER(38,8), 
	"SUPRIDORA5" NVARCHAR2(100), 
	"NIVEL_TENSAO5" NVARCHAR2(100), 
	"MWH5" NUMBER(38,8), 
	"DESCONTO5_PERCENT" NUMBER(38,8), 
	"TARIFA5_RS_MWH" NUMBER(38,8), 
	"TARIFA_COBERTURA5_RS_MWH" NUMBER(38,8), 
	"DESCONTO_ANTIGO5_PERCENT" NUMBER(38,8)
   )
   
   
 --PERSAS ENERGIA
 CREATE TABLE "IRARRR01"."PERSAS_ENERGIA" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"MERCADO_LIVRE_MWH" NUMBER(38,8), 
	"MERCADO_A1_MWH" NUMBER(38,8), 
	"MERCADO_BT_MWH" NUMBER(38,8), 
	"GERACAO_PROPRIA_MWH" NUMBER(38,8), 
	"PROINFA_MWH" NUMBER(38,8), 
	"SUPRIMENTO_MWH" NUMBER(38,8), 
	"ANGRA_MWH" NUMBER(38,8), 
	"CCGF_MWH" NUMBER(38,8), 
	"CONTRATOS_BILATERAIS_MWH" NUMBER(38,8), 
	"GERACAO_PROPRIA_RS" NUMBER(38,8), 
	"PROINFA_RS" NUMBER(38,8), 
	"SUPRIMENTO_RS" NUMBER(38,8), 
	"ANGRA_RS" NUMBER(38,8), 
	"CCGF_RS" NUMBER(38,8), 
	"CONTRATOS_BILATERAIS_RS" NUMBER(38,8), 
	"GERACAO_PROPRIA_RS_MWH" NUMBER(38,8), 
	"PROINFA_RS_MWH" NUMBER(38,8), 
	"SUPRIMENTO_RS_MWH" NUMBER(38,8), 
	"ANGRA_RS_MWH" NUMBER(38,8), 
	"CCGF_RS_MWH" NUMBER(38,8), 
	"CONTRATOS_BILATERAIS_RS_MWH" NUMBER(38,8)
   )
   
   
 --PERSAS FINANCEIROS
 CREATE TABLE "IRARRR01"."PERSAS_FINANCEIROS" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"NEUTRALIDADE_TOTAL_RS" NUMBER(38,8), 
	"TOTAL_FINANCEIRO_RS" NUMBER(38,8)
   )
   
   
 --PERSAS INDICES
 CREATE TABLE "IRARRR01"."PERSAS_INDICES" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"IRT_ECONOMICO_PERCENT" NUMBER(38,8), 
	"IRT_FINANCEIRO_PERCENT" NUMBER(38,8), 
	"IRT_FINAN_ECON_PERCENT" NUMBER(38,8), 
	"EFEITO_MEDIO_AT_PERCENT" NUMBER(38,8), 
	"EFEITO_MEDIO_BT_PERCENT" NUMBER(38,8), 
	"EFEITO_TARIFA_AT_BT_PERCENT" NUMBER(38,8), 
	"TARIFA_RESIDEN_B1_RS_MWH" NUMBER(38,8), 
	"ICMS_PERCENT" NUMBER(38,8), 
	"PIS_PERCENT" NUMBER(38,8)
   )
   
   
 --PERSAS SUBSIDIOS
 CREATE TABLE "IRARRR01"."PERSAS_SUBSIDIOS" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"SUBSIDIO_CARGA_RS" NUMBER(38,8), 
	"SUBSIDIO_GERACAO_RS" NUMBER(38,8), 
	"SUBSIDIO_DISTRIBUICAO_RS" NUMBER(38,8), 
	"SUBSIDIO_AGUA_RS" NUMBER(38,8), 
	"SUBSIDIO_RURAL_RS" NUMBER(38,8), 
	"SUBSIDIO_IRRIGANTE_RS" NUMBER(38,8)
   )
   
   
 --PERSAS TI CAA
 CREATE TABLE "IRARRR01"."PERSAS_TI_CAA" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"ATIVO_IMOBILIZADO_RS" NUMBER(38,8), 
	"OBRIGACOES_ESPECIAIS_BRUTA_RS" NUMBER(38,8), 
	"BENS_TOTAL_DEPRECIADOS_RS" NUMBER(38,8), 
	"BASE_REMUN_BRUTA_RS" NUMBER(38,8), 
	"DEPRECIACAO_ACUMULADA_PERCENT" NUMBER(38,8), 
	"VBR_RS" NUMBER(38,8), 
	"OBRIGACOES_ESPECIAIS_LIQUIDA_RS" NUMBER(38,8), 
	"TERRENOS_RS" NUMBER(38,8), 
	"ALMOXARIFADO_RS" NUMBER(38,8), 
	"BASE_REMUNERACAO_LIQUIDA_RS" NUMBER(38,8), 
	"TAXA_DEPRECIACAO_PERCENT" NUMBER(38,8), 
	"RWACCPRE_PERCENT" NUMBER(38,8), 
	"REMUNERACAO_CAPITAL_RS" NUMBER(38,8), 
	"QRR_RS" NUMBER(38,8), 
	"BAR_RS" NUMBER(38,8), 
	"BARA_RS" NUMBER(38,8), 
	"BARV_RS" NUMBER(38,8), 
	"BARI_RS" NUMBER(38,8), 
	"CAL_RS" NUMBER(38,8), 
	"CAV_RS" NUMBER(38,8), 
	"CAI_RS" NUMBER(38,8), 
	"CAIMI_RS" NUMBER(38,8)
   )
   
 --PERSAS TI CAOM
 CREATE TABLE "IRARRR01"."PERSAS_TI_CAOM" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"REGIAO" NVARCHAR2(100), 
	"DATA" NVARCHAR2(100), 
	"UNIDADES_CONSUMIDORAS" NUMBER(38,8), 
	"REDES_DISTRIBUICAO_KM" NUMBER(38,8), 
	"CO_DIVIDIDO_UC_RS_UC" NUMBER(38,8), 
	"CUSTOS_OPERACIONAIS_RS" NUMBER(38,8), 
	"RESIDENCIAL_RECEITA_PERCENT" NUMBER(38,8), 
	"INDUSTRIAL_RECEITA_PERCENT" NUMBER(38,8), 
	"COMERCIAL_RECEITA_PERCENT" NUMBER(38,8), 
	"RURAL_RECEITA_PERCENT" NUMBER(38,8), 
	"ILUMINACAO_RECEITA_PERCENT" NUMBER(38,8), 
	"PODER_PUBLICO_RECEITA_PERCENT" NUMBER(38,8), 
	"SERV_PUBLICO_RECEITA_PERCENT" NUMBER(38,8), 
	"DEMAIS_RECEITA_PERCENT" NUMBER(38,8), 
	"RESIDENCIAL_RI_PERCENT" NUMBER(38,8), 
	"INDUSTRIAL_RI_PERCENT" NUMBER(38,8), 
	"COMERCIAL_RI_PERCENT" NUMBER(38,8), 
	"RURAL_RI_PERCENT" NUMBER(38,8), 
	"ILUMINACAO_RI_PERCENT" NUMBER(38,8), 
	"PODER_PUBLICO_RI_PERCENT" NUMBER(38,8), 
	"SERV_PUBLICO_RI_PERCENT" NUMBER(38,8), 
	"DEMAIS_RI_PERCENT" NUMBER(38,8), 
	"NIVEL_REGULATORIO_RI_PERCENT" NUMBER(38,8), 
	"BASE_CALCULO_RI_RS" NUMBER(38,8), 
	"RECEITAS_IRRECUPERAVEIS_RS" NUMBER(38,8)
   )