 CREATE TABLE SPARTA_CAPA
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100)
);
 
 
 
 --SPARTA DISTRIBUIDORAS
CREATE TABLE SPARTA_DISTRIBUIDORAS
("ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"SARI" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"PERIODO_TARIFARIO" NUMBER(38,8)
);


--SPARTA ESTADOS
CREATE TABLE SPARTA_ESTADOS
(
"UF" NVARCHAR2(10), 
"NOME" NVARCHAR2(1000)
);
 
 
 
--SPARTA GRUPO ECONOMICO
CREATE TABLE SPARTA_GRUPO_ECONOMICO
(
    "ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000),
    "GRUPO_ECONOMICO" NVARCHAR2(100)
);
 
 
 --SPARTA NUC
 CREATE TABLE SPARTA_NUC(
 "CHAVE" NVARCHAR2(100)
 ,"EVENTO_TARIFARIO" NVARCHAR2(10)
 ,"ANO" NVARCHAR2(10)
 ,"ID" NVARCHAR2(10)
 ,"DISTRIBUIDORA" NVARCHAR2(1000)
 ,"UF" NVARCHAR2(10)
 ,"DATA" NVARCHAR2(100)
 ,"PERIODO_TARIFARIO" NUMBER(38,8)
 ,"CONTRATO" NVARCHAR2(100)
 ,"RESIDENCIAL" NUMBER(38,8)
 ,"INDUSTRIAL" NUMBER(38,8)
 ,"COMERCIAL" NUMBER(38,8)
 ,"RURAL" NUMBER(38,8)
 ,"ILUMINACAO" NUMBER(38,8)
 ,"PODER_PUBLICO" NUMBER(38,8)
 ,"SERVICO_PUBLICO" NUMBER(38,8)
 ,"DEMAIS" NUMBER(38,8)
 ,"A1" NUMBER(38,8)
 ,"A2" NUMBER(38,8)
 ,"A3" NUMBER(38,8)
 ,"A3A" NUMBER(38,8)
 ,"A4" NUMBER(38,8)
 ,"AS" NUMBER(38,8)
 ,"BT" NUMBER(38,8)
 );
 
 
 
 --SPARTA MERCADO
 CREATE TABLE SPARTA_MERCADO 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
	"RESIDENCIAL_MWH" NUMBER(38,8), 
	"INDUSTRIAL_MWH" NUMBER(38,8), 
	"COMERCIAL_MWH" NUMBER(38,8), 
	"RURAL_MWH" NUMBER(38,8), 
	"ILUMINACAO_MWH" NUMBER(38,8), 
	"PODER_PUBLICO_MWH" NUMBER(38,8), 
	"SERVICO_PUBLICO_MWH" NUMBER(38,8), 
	"DEMAIS_MWH" NUMBER(38,8), 
    "FORNECIMENTO_MWH" NUMBER(38,8),
	"A1_MWH" NUMBER(38,8), 
	"A2_MWH" NUMBER(38,8), 
	"A3_MWH" NUMBER(38,8), 
	"A3A_MWH" NUMBER(38,8), 
	"A4_MWH" NUMBER(38,8), 
	"AS_MWH" NUMBER(38,8), 
	"BT_MWH" NUMBER(38,8),
    "SUPRIMENTO_MWH" NUMBER(38,8),
    "LIVRES_A1_MWH" NUMBER(38,8),
    "DEMAIS_LIVRES_MWH" NUMBER(38,8),
    "DISTRIBUICAO_MWH" NUMBER(38,8),
    "GERADOR_MWH" NUMBER(38,8),
    "MERCADO_BAIXA_RENDA_MWH" NUMBER(38,8),
    "TOTAL_MWH" NUMBER(38,8),
    "ANO_ANTERIOR_MWH" NUMBER(38,8),
    "VARIACAO_PERCENT" NUMBER(38,8)
   );
   
   
--SPARTA RECEITA
  CREATE TABLE SPARTA_RECEITA 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
	"RESIDENCIAL_RS" NUMBER(38,8), 
	"INDUSTRIAL_RS" NUMBER(38,8), 
	"COMERCIAL_RS" NUMBER(38,8), 
	"RURAL_RS" NUMBER(38,8), 
	"ILUMINACAO_RS" NUMBER(38,8), 
	"PODER_PUBLICO_RS" NUMBER(38,8), 
	"SERVICO_PUBLICO_RS" NUMBER(38,8), 
	"DEMAIS_RS" NUMBER(38,8), 
	"FORNECIMENTO_RS" NUMBER(38,8), 
	"A1_RS" NUMBER(38,8), 
	"A2_RS" NUMBER(38,8), 
	"A3_RS" NUMBER(38,8), 
	"A3A_RS" NUMBER(38,8), 
	"A4_RS" NUMBER(38,8), 
	"AS_RS" NUMBER(38,8), 
	"BT_RS" NUMBER(38,8), 
	"SUPRIMENTO_RS" NUMBER(38,8), 
	"LIVRES_A1_RS" NUMBER(38,8), 
	"DEMAIS_LIVRES_RS" NUMBER(38,8), 
	"DISTRIBUICAO_RS" NUMBER(38,8), 
	"GERADOR_RS" NUMBER(38,8), 
	"TOTAL_RS" NUMBER(38,8)
   );
   
 
 --SPARTA FATOR X
 CREATE TABLE SPARTA_FATOR_X
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100),
"IGPM_PERCENT" NUMBER(38,8)
,"IPCA_PERCENT" NUMBER(38,8)
,"COMPONENTE_PD_PERCENT" NUMBER(38,8)
,"COMPONENTE_T_PERCENT" NUMBER(38,8)
,"COMPONENTE_Q_PERCENT" NUMBER(38,8)
,"FATOR_X_PERCENT" NUMBER(38,8)
,"IVI_X_PERCENT" NUMBER(38,8) 

 );
 
 
 --SPARTA INDICES
 CREATE TABLE SPARTA_INDICES
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100),
"IRT_ECONOMICO_PERCENT" NUMBER(38,8)
,"IRT_FINANCEIRO_PERCENT" NUMBER(38,8)
,"IRT_FINAN_ECON_PERCENT" NUMBER(38,8)
,"EFEITO_AT_PERCENT" NUMBER(38,8)
,"EFEITO_BT_PERCENT" NUMBER(38,8)
,"EFEITO_TARIFA_AT_BT_PERCENT" NUMBER(38,8)
,"TARIFA_RESIDEN_B1_RS" NUMBER(38,8) 
,"ICMS_PERCENT" NUMBER(38,8) 
,"PIS_PERCENT" NUMBER(38,8) 
,"PERDAS_RB_MWH" NUMBER(38,8) 
,"PERDAS_DITS_MWH" NUMBER(38,8) 

 );
 
 
 
 --SPARTA DRP
 CREATE TABLE SPARTA_DRP
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100)
,"ENCARGOS_RS" NUMBER(38,8)
,"RGR_RS" NUMBER(38,8)
,"CCC_RS" NUMBER(38,8)
,"TFSEE_RS" NUMBER(38,8)
,"CDE_TOTAL_RS" NUMBER(38,8) 
,"CFURH_RS" NUMBER(38,8) 
,"ESS_EER_RS" NUMBER(38,8)
,"PROINFA_RS" NUMBER(38,8)
,"PD_RS" NUMBER(38,8)
,"ONS_RS" NUMBER(38,8)
,"TRANSPORTE_RS" NUMBER(38,8)
,"REDE_BASICA_RS" NUMBER(38,8)
,"REDE_BASICA_FRONTEIRA_RS" NUMBER(38,8)
,"REDE_BASICA_ONS_A2_RS" NUMBER(38,8)
,"REDE_BASICA_EXPORT_A2_RS" NUMBER(38,8)
,"MUST_ITAIPU_RS" NUMBER(38,8)
,"TRANSPORTE_ITAIPU_RS" NUMBER(38,8)
,"CONEXAO_RS" NUMBER(38,8)
,"SISTEMA_DISTRIBUICAO_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_RS" NUMBER(38,8)
,"RECEITA_IRRECUPERAVEL_RS" NUMBER(38,8)
,"PARCELA_A_RS" NUMBER(38,8)
,"PARCELA_B_RS" NUMBER(38,8)
,"RA1_RS" NUMBER(38,8)
,"PARCELA_EER_RS" NUMBER(38,8)
,"PARCELA_ESS_RS" NUMBER(38,8)
,"CDE_USO_RS" NUMBER(38,8)
,"CDE_ENERGIA_RS" NUMBER(38,8) 
,"CDE_ENERGIA_ACR_RS" NUMBER(38,8) 
,"CDE_ELETROBAS_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_MWH" NUMBER(38,8)
,"FORNECIMENTO_SUPRIMENTO_MWH" NUMBER(38,8)
,"FORNECIMENTO_MWH" NUMBER(38,8)
,"SUPRIMENTO_TE_MWH" NUMBER(38,8)
,"CUSTO_MEDIO_RS_MWH" NUMBER(38,8)
,"PERDAS_REGULATORIAS_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_MWH" NUMBER(38,8)
,"PERDA_TECNICA_MWH" NUMBER(38,8)
,"PERDA_RB_DISTRIBUICAO_MWH" NUMBER(38,8)
,"PERDA_RB_CATIVO_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_REDE_BASICA_PERCENT" NUMBER(38,8)


 );
 
 
 
 --SPARTA DRA
CREATE TABLE SPARTA_DRA
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100)
,"ENCARGOS_RS" NUMBER(38,8)
,"RGR_RS" NUMBER(38,8)
,"CCC_RS" NUMBER(38,8)
,"TFSEE_RS" NUMBER(38,8)
,"CDE_TOTAL_RS" NUMBER(38,8) 
,"CFURH_RS" NUMBER(38,8) 
,"ESS_EER_RS" NUMBER(38,8)
,"PROINFA_RS" NUMBER(38,8)
,"PD_RS" NUMBER(38,8)
,"ONS_RS" NUMBER(38,8)
,"TRANSPORTE_RS" NUMBER(38,8)
,"REDE_BASICA_RS" NUMBER(38,8)
,"REDE_BASICA_FRONTEIRA_RS" NUMBER(38,8)
,"REDE_BASICA_ONS_A2_RS" NUMBER(38,8)
,"REDE_BASICA_EXPORT_A2_RS" NUMBER(38,8)
,"MUST_ITAIPU_RS" NUMBER(38,8)
,"TRANSPORTE_ITAIPU_RS" NUMBER(38,8)
,"CONEXAO_RS" NUMBER(38,8)
,"SISTEMA_DISTRIBUICAO_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_RS" NUMBER(38,8)
,"RECEITA_IRRECUPERAVEL_RS" NUMBER(38,8)
,"PARCELA_A_RS" NUMBER(38,8)
,"PARCELA_B_RS" NUMBER(38,8)
,"RA0_RS" NUMBER(38,8)
,"ENERGIA_COMPRADA_MWH" NUMBER(38,8)
,"FORNECIMENTO_SUPRIMENTO_MWH" NUMBER(38,8)
,"FORNECIMENTO_MWH" NUMBER(38,8)
,"SUPRIMENTO_TE_MWH" NUMBER(38,8)
,"CUSTO_MEDIO_RS_MWH" NUMBER(38,8)
,"PERDAS_REGULATORIAS_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_MWH" NUMBER(38,8)
,"PERDA_TECNICA_MWH" NUMBER(38,8)
,"PERDA_RB_DISTRIBUICAO_MWH" NUMBER(38,8)
,"PERDA_RB_CATIVO_MWH" NUMBER(38,8)
,"PERDA_NAO_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_TECNICA_PERCENT" NUMBER(38,8)
,"PERDA_REDE_BASICA_PERCENT" NUMBER(38,8)



 );
 
 
 
  --SPARTA CVA
CREATE TABLE "IRARRR01"."SPARTA_CVA" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
	"5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"CCC_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"CDE_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
    "CDE_COVID_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8),
	"REDE_BASICA_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"COMPRA_ENERGIA_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"CFURH_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"TRANSPORTE_ITAIPU_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"PROINFA_12_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"ESS_ERR_5_DIA_UTIL_ANTERIOR_RS" NUMBER(38,8), 
	"12_MESES_SUBSEQUENTES_RS" NUMBER(38,8), 
	"CCC_12_MESES_SUB_RS" NUMBER(38,8), 
	"CDE_12_MESES_SUB_RS" NUMBER(38,8), 
    "CDE_COVID_12_MESES_SUB_RS" NUMBER(38,8), 
	"REDE_BASICA_12_MESES_SUB_RS" NUMBER(38,8), 
	"COMPRA_ENERGIA_12_MESES_SUB_RS" NUMBER(38,8), 
	"CFURH_12_MESES_SUB_RS" NUMBER(38,8), 
	"TRANSPORTE_ITAIPU_12_MESES_SUB_RS" NUMBER(38,8), 
	"PROINFA_12_MESES_SUB_RS" NUMBER(38,8), 
	"ESS_ERR_12_MESES_SUB_RS" NUMBER(38,8), 
	"SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"CCC_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"CDE_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"REDE_BASICA_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"COMPRA_ENERGIA_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"CFURH_12_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"TRANSPORTE_ITAIPU_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"PROINFA_12_SALDO_COMPENSAR_RS" NUMBER(38,8), 
	"ESS_ERR_SALDO_COMPENSAR_RS" NUMBER(38,8)
   )
 
 
 
 
 --SPARTA SUBSIDIOS
 CREATE TABLE SPARTA_SUBSIDIOS
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100),
"SUBSIDIO_CARGA_RS" NUMBER(38,8)
,"SUBSIDIO_GERACAO_RS" NUMBER(38,8)
,"SUBSIDIO_DISTRIBUICAO_RS" NUMBER(38,8)
,"SUBSIDIO_AGUA_RS" NUMBER(38,8) 
,"SUBSIDIO_RURAL_RS" NUMBER(38,8) 
,"SUBSIDIO_IRRIGANTE_RS" NUMBER(38,8)

 );
 
 
 
 
 --SPARTA FINANCEIRO
 CREATE TABLE SPARTA_FINANCEIRO
 (
"CHAVE" NVARCHAR2(100), 
"EVENTO_TARIFARIO" NVARCHAR2(10), 
"ANO" NVARCHAR2(10), 
"ID" NVARCHAR2(10), 
"DISTRIBUIDORA" NVARCHAR2(1000), 
"UF" NVARCHAR2(10), 
"DATA" NVARCHAR2(100), 
"PERIODO_TARIFARIO" NUMBER(38,8), 
"CONTRATO" NVARCHAR2(100),
"DOLAR_MEDIO_RS" NUMBER(38,8)
,"CVA_TOTAL_RS" NUMBER(38,8)
,"SALDO_CVA_TOTAL_RS" NUMBER(38,8)
,"NEUTRALIDADE_TOTAL_RS" NUMBER(38,8) 
,"SOBRECONTRATACAO_TOTAL_RS" NUMBER(38,8) 
,"PREVISAO_RISCO_HIDROLOGICO_TOTAL_RS" NUMBER(38,8)
,"REVERSAO_RISCO_HIDROLOGICO_TOTAL_RS" NUMBER(38,8)
,"ESCASSEZ_HIDRICA_TOTAL_RS" NUMBER(38,8)
,"CREDITOS_PIS_RS" NUMBER(38,8)
,"TOTAL_FINANCEIRO_RS" NUMBER(38,8)

 );
 
 
 
--SPARTA ENERGIA
CREATE TABLE "IRARRR01"."SPARTA_ENERGIA" 
   (	"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100),  
	"ENERGIA_BASE_MWH" NUMBER(38,8), 
	"GERACAO_PROPRIA_MWH" NUMBER(38,8), 
	"COTA_ANGRA_MWH" NUMBER(38,8), 
	"COTAS_LEI_12783_MWH" NUMBER(38,8), 
	"ITAIPU_MWH" NUMBER(38,8), 
	"PROINFA_MWH" NUMBER(38,8), 
	"BILATERAL_MWH" NUMBER(38,8), 
	"CCEAR_MWH" NUMBER(38,8),  
	"ENERGIA_BASE_RS" NUMBER(38,8), 
	"GERACAO_PROPRIA_RS" NUMBER(38,8), 
	"COTA_ANGRA_RS" NUMBER(38,8), 
	"COTAS_LEI_12783_RS" NUMBER(38,8), 
	"ITAIPU_RS" NUMBER(38,8), 
	"PROINFA_RS" NUMBER(38,8), 
	"BILATERAL_RS" NUMBER(38,8), 
	"CCEAR_RS" NUMBER(38,8), 
	"ENERGIA_BASE_RS_MWH" NUMBER(38,8), 
	"GERACAO_PROPRIA_RS_MWH" NUMBER(38,8), 
	"COTA_ANGRA_RS_MWH" NUMBER(38,8), 
	"COTAS_LEI_12783_RS_MWH" NUMBER(38,8), 
	"ITAIPU_RS_MWH" NUMBER(38,8), 
	"PROINFA_RS_MWH" NUMBER(38,8), 
	"BILATERAL_RS_MWH" NUMBER(38,8), 
	"CCEAR_RS_MWH" NUMBER(38,8),  
	"ENERGIA_INVERSAO_MWH" NUMBER(38,8)
   );


 
--SPARTA AJ CO CALCULO COMP T
CREATE TABLE SPARTA_RTP_AJ_CO_CALCULO_COMP_T(
"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
    "AJ_PARCELA_B_RS" NUMBER(38,8),
    "PARTICIPACAO_CO_ANTES_AJ_PERCENT" NUMBER(38,8),
    "AJ_CUSTO_OPERACIONAL_RS" NUMBER(38,8)
);
 

 --SPARTA CAA
 CREATE TABLE SPARTA_RTP_CAA(
"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
    "BAR_RS" NUMBER(38,8),
    "BARA_RS" NUMBER(38,8),
    "BARV_RS" NUMBER(38,8),
    "BARI_RS" NUMBER(38,8),
    "CAL_RS" NUMBER(38,8),
    "CAV_RS" NUMBER(38,8),
    "CAI_RS" NUMBER(38,8),
    "CAIMI_RS" NUMBER(38,8),
    "ATIVO_IMOBILIZADO_RS" NUMBER(38,8),
    "INDICE_APROVEITAMENTO_INTEGRAL_RS" NUMBER(38,8),
    "OBRIGACOES_ESPECIAIS_BRUTA_RS" NUMBER(38,8),
    "BENS_TOTAL_DEPRECIADOS_RS" NUMBER(38,8),
    "BASE_REMUN_BRUTA_RS" NUMBER(38,8),
    "DEPRECIACAO_ACUMULADA_RS" NUMBER(38,8),
    "AIS_LIQUIDO_RS" NUMBER(38,8),
    "INDICE_APROVEITAMENTO_DEPRECIADO_RS" NUMBER(38,8),
    "VBR_RS" NUMBER(38,8),
    "ALMOXARIFADO_OPERACAO_RS" NUMBER(38,8),
    "ATIVO_DIFERIDO_RS" NUMBER(38,8),
    "OBRIGACOES_ESPECIAIS_LIQUIDA_RS" NUMBER(38,8),
    "TERRENOS_SERVIDOES_RS" NUMBER(38,8),
    "BASE_REMUN_LIQUIDA_RS" NUMBER(38,8),
    "SALDO_RGR_PLPT_RS" NUMBER(38,8),
    "SALDO_RGR_DEMAIS_INVEST_RS" NUMBER(38,8),
    "TAXA_DEPRECIACAO_PERCENT" NUMBER(38,8),
    "QRR_RS" NUMBER(38,8),
    "RC_SEM_OBRIGACOES_ESPECIAIS_RS" NUMBER(38,8),
    "REMUN_OBRIGACOES_ESPECIAIS_RS" NUMBER(38,8),
    "RC_RS" NUMBER(38,8),
    "WACC_REAL_ANTES_IMPOSTO_PERCENT" NUMBER(38,8),
    "TAXA_RGR_PLPT_REAL_PERCENT" NUMBER(38,8),
    "TAXA_RGR_DEMAIS_INVEST_PERCENT" NUMBER(38,8),
    "CAA_RCOE_RS" NUMBER(38,8),
    "CAOM_DIVIDIDO_POR_CAOM_CAA_RCOE_PERCENT" NUMBER(38,8),
    "PARTICIPACAO_CAPITAL_PROPRIO_PERCENT" NUMBER(38,8),
    "PRN_PRP_PERCENT" NUMBER(38,8),
    "IMPOSTO_RENDA_PERCENT" NUMBER(38,8),
    "RC_OBRIGACOES_ESPECIAIS_RS" NUMBER(38,8)
    
);


--SPARTA CAOM
CREATE TABLE SPARTA_RTP_CAOM(
"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
    "RECEITA_PARCELA_B_ANO_TESTE_RS" NUMBER(38,8),
"CO_ULTIMA_REVISAO_AJUSTES_RS" NUMBER(38,8),
"VPB_ULTIMA_REVISAO_AJUSTES_RS" NUMBER(38,8),
"COMPONENTE_T_ULTIMA_REVISAO_PERCENT" NUMBER(38,8),
"FATOR_N_MENOS_1_PERCENT" NUMBER(38,8),
"RECEITA_CO_ANO_TESTE_RS" NUMBER(38,8),
"LIMITE_SUPERIOR_CO_EFICIENTE_RS" NUMBER(38,8),
"LIMITE_INFERIOR_CO_EFICIENTE_RS" NUMBER(38,8),
"CO_EFICIENTE_RS" NUMBER(38,8),
"VARIACAO_ANUAL_CO_SEM_LIMITE_PERCENT" NUMBER(38,8),
"VARIACAO_ANUAL_CO_LIMITADA_PERCENT" NUMBER(38,8),
"META_CO_SEM_COMPARTILHAMENTO_RS" NUMBER(38,8),
"OPEX_MEDIO_RS" NUMBER(38,8),
"RAZAO_ENTRE_CO_AJUSTADO_E_OPEX_MEDIO_PERCENT" NUMBER(38,8),
"META_CO_REGULATORIO_RS" NUMBER(38,8),
"CO_REGULATORIO_RS" NUMBER(38,8),
"IPCA_MES_ANTERIOR_DATA_REVISAO_TARIFARIA_RS" NUMBER(38,8),
"IPCA_MES_ANTERIOR_DATA_CALCULO_EFICIENCIA_RS" NUMBER(38,8),
"CUSTO_EFICIENTE_DATA_CALCULO_EFICIENCIA_RS" NUMBER(38,8),
"CUSTO_EFICIENTE_DATA_REVISAO_TARIFARIA_RS" NUMBER(38,8),
"FATOR_ATUALIZACAO_ALPHA" NUMBER(38,8),
"REFERENCIA_EFICIENCIA_MEDIA_PERCENT" NUMBER(38,8),
"EFICIENCIA_APURADA_PERCENT" NUMBER(38,8),
"LIMITE_SUPERIOR_INTERVALO_EFICIENCIA_PERCENT" NUMBER(38,8),
"LIMITE_INFERIOR_INTERVALO_EFICIENCIA_PERCENT" NUMBER(38,8),
"CO_REAL_ESTUDO_EFICIENCIA" NUMBER(38,8),
"IPCA_JUNHO_ANO_MENOS_2" NUMBER(38,8),
"IPCA_DEZEMBRO_ANO_MENOS_2" NUMBER(38,8),
"CONTA_PESSOAL_ANO_MENOS_2_RS" NUMBER(38,8),
"CONTA_MATERIAIS_ANO_MENOS_2_RS" NUMBER(38,8),
"CONTA_TERCEIROS_ANO_MENOS_2_RS" NUMBER(38,8),
"CONTA_SEGUROS_ANO_MENOS_2_RS" NUMBER(38,8),
"CONTA_TRIBUTOS_ANO_MENOS_2_RS" NUMBER(38,8),
"CONTA_OUTROS_ANO_MENOS_2_RS" NUMBER(38,8),
"DEMAIS_CUSTOS_ANO_MENOS_2_RS" NUMBER(38,8),
"CO_ANO_MENOS_2_RS" NUMBER(38,8),
"CO_ATUALIZADO_ANO_MENOS_2_RS" NUMBER(38,8),
"IPCA_JUNHO_ANO_MENOS_1" NUMBER(38,8),
"IPCA_DEZEMBRO_ANO_MENOS_1" NUMBER(38,8),
"CONTA_PESSOAL_ANO_MENOS_1_RS" NUMBER(38,8),
"CONTA_MATERIAIS_ANO_MENOS_1_RS" NUMBER(38,8),
"CONTA_TERCEIROS_ANO_MENOS_1_RS" NUMBER(38,8),
"CONTA_SEGUROS_ANO_MENOS_1_RS" NUMBER(38,8),
"CONTA_TRIBUTOS_ANO_MENOS_1_RS" NUMBER(38,8),
"CONTA_OUTROS_ANO_MENOS_1_RS" NUMBER(38,8),
"DEMAIS_CUSTOS_ANO_MENOS_1_RS" NUMBER(38,8),
"CO_ANO_MENOS_1_RS" NUMBER(38,8),
"CO_ATUALIZADO_ANO_MENOS_1_RS" NUMBER(38,8),
"INDICADOR_MEDIO_PNT_PERCENT" NUMBER(38,8),
"META_PERCENT" NUMBER(38,8),
"DEC_GLOBAL_MEDIO_REALIZADO" NUMBER(38,8),
"LIMITE_V8_GLOBAL" NUMBER(38,8),
"PESO_INSUMO_U" NUMBER(38,8),
"FATOR_ESCALA_PERCENT" NUMBER(38,8),
"REDES_SUBTERRANEAS_KM" NUMBER(38,8),
"REDE_DISTRIBUICAO_AREA_KM" NUMBER(38,8),
"REDE_ALTA_TENSAO_KM" NUMBER(38,8),
"NUMERO_CONSUMIDORES" NUMBER(38,8),
"PNT_AJUSTADA_MWH" NUMBER(38,8),
"CHI_AJUSTADO_HORAS" NUMBER(38,8),
"MERCADO_PONDERADO_MWH" NUMBER(38,8),
"MERCADO_AT_MWH" NUMBER(38,8),
"MERCADO_MT_MWH" NUMBER(38,8),
"MERCADO_BT_MWH" NUMBER(38,8),
"FATOR_ESCALA_PESO" NUMBER(38,8),
"REDES_SUBTERRANEAS_PESO" NUMBER(38,8),
"REDE_DISTRIBUICAO_AREA_PESO" NUMBER(38,8),
"REDE_ALTA_TENSAO_PESO" NUMBER(38,8),
"NUMERO_CONSUMIDORES_PESO" NUMBER(38,8),
"PNT_AJUSTADA_PESO" NUMBER(38,8),
"CHI_AJUSTADO_PESO" NUMBER(38,8),
"MERCADO_PONDERADO_PESO" NUMBER(38,8),
"MERCADO_AT_PESO" NUMBER(38,8),
"MERCADO_MT_PESO" NUMBER(38,8),
"MERCADO_BT_PESO" NUMBER(38,8),
"OUTRAS_RECEITAS_RS" NUMBER(38,8),
"EXCEDENTE_REATIVOS_RS" NUMBER(38,8),
"ULTRAPASSAGEM_DEMANDA_RS" NUMBER(38,8),
"PARCELA_B_DEDUZIDAS_OUTRAS_RECEITAS_RS" NUMBER(38,8)

    
);


--SPARTA RI
CREATE TABLE SPARTA_RTP_RI(
"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 

"RI_ENCARGOS_SETORIAIS_RS" NUMBER(38,8),
"ENCARGOS_DRP_RS" NUMBER(38,8),
"CARGA_TRIBUTARIA_PERCENT" NUMBER(38,8),
"LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"DEMAIS_RI_RS" NUMBER(38,8),
"RECEITA_ADICIONAL_BANDEIRA_RS" NUMBER(38,8),
"ENERGIA_COMPRADA_RS" NUMBER(38,8),
"TRANSPORTE_ENERGIA_RS" NUMBER(38,8),
"LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"RI_TOTAL_RS" NUMBER(38,8),
"RESIDENCIAL_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"INDUSTRIAL_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"COMERCIAL_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"RURAL_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"PODER_PUBLICO_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"ILUMINACAO_PUBLICA_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"SERVICO_PUBLICO_PARTIPACAO_CONSUMO_PERCENT" NUMBER(38,8),
"RESIDENCIAL_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"INDUSTRIAL_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"COMERCIAL_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"RURAL_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"PODER_PUBLICO_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"ILUMINACAO_PUBLICA_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"SERVICO_PUBLICO_LIMITE_DEMAIS_RI_PERCENT" NUMBER(38,8),
"RESIDENCIAL_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"INDUSTRIAL_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"COMERCIAL_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"RURAL_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"PODER_PUBLICO_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"ILUMINACAO_PUBLICA_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"SERVICO_PUBLICO_MEDIANA_INADIMPLENCIAS_PERCENT" NUMBER(38,8),
"RESIDENCIAL_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"INDUSTRIAL_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"COMERCIAL_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"RURAL_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"PODER_PUBLICO_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"ILUMINACAO_PUBLICA_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"SERVICO_PUBLICO_LIMITE_NEUTRALIDADE_PERCENT" NUMBER(38,8),
"RESIDENCIAL_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"INDUSTRIAL_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"COMERCIAL_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"RURAL_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"PODER_PUBLICO_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"ILUMINACAO_PUBLICA_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8),
"SERVICO_PUBLICO_LIMITE_RI_ENCARGOS_PERCENT" NUMBER(38,8)

    
);


--SPARTA COR
CREATE TABLE SPARTA_RTP_COR(
"CHAVE" NVARCHAR2(100), 
	"EVENTO_TARIFARIO" NVARCHAR2(10), 
	"ANO" NVARCHAR2(10), 
	"ID" NVARCHAR2(10), 
	"DISTRIBUIDORA" NVARCHAR2(1000), 
	"UF" NVARCHAR2(10), 
	"DATA" NVARCHAR2(100), 
	"PERIODO_TARIFARIO" NUMBER(38,8), 
	"CONTRATO" NVARCHAR2(100), 
"THETA_INF" NUMBER(38,12),
"THETA_CENTRO" NUMBER(38,12),
"THETA_SUP" NUMBER(38,12),
"THETA_REF" NUMBER(38,12),
"OPEX_REAL" NUMBER(38,12),
"PMSO_CORRIGIDO" NUMBER(38,12),
"FATOR_ESCALA" NUMBER(38,12),
"U" NUMBER(38,12),
"VS_YRSUB" NUMBER(38,12),
"VS_YRDIST_A" NUMBER(38,12),
"VS_YRALTA" NUMBER(38,12),
"VS_YCONS" NUMBER(38,12),
"VS_YMPONDERADO" NUMBER(38,12),
"VS_YD_PERDAS_DIF2" NUMBER(38,12),
"VS_YD_DEC_V8" NUMBER(38,12),
"P_AT" NUMBER(38,12),
"P_MT" NUMBER(38,12),
"P_BT" NUMBER(38,12),
"PMSO_2013" NUMBER(38,12),
"CONT_ASSOCIATIVA" NUMBER(38,12),
"PESO_AT_PERCENT" NUMBER(38,12),
"PESO_MT_PERCENT" NUMBER(38,12),
"PESO_BT_PERCENT" NUMBER(38,12)

    
);
